<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <AssemblyName>S7TrendMonitor</AssemblyName>
    <RootNamespace>S7TrendMonitor</RootNamespace>
    <PlatformTarget>x86</PlatformTarget>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="app.ico">
      <LogicalName>S7TrendMonitor.app.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="S7NetPlus" Version="0.20.0" />
    <PackageReference Include="ScottPlot.WinForms" Version="5.1.59" />
    <PackageReference Include="System.IO.Ports" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="libs\libnodave.dll">
      <LogicalName>libnodave.dll</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
